name: 📈 Daily Fibonacci Email Bot

on:
  schedule:
    - cron: '30 3 * * 1-5'  # 9:00 AM IST (UTC+5:30)
  workflow_dispatch:

jobs:
  send-signals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run signal bot
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python fib_signal_bot.py
